###############################################
###
##   File:   AdvanceTime.rb
##   Desc:   Advance Time
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class AdvanceTime < IseMessage
  def initialize
    super
    desc "Advance Time"
  end
end
