###############################################
###
##   File:   EndCaseComplete.rb
##   Desc:   End Case Completed
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class EndCaseComplete < IseMessage
  def initialize
    super
    desc "End Case Completed"
  end
end
