###############################################
###
##   File:   EndCase.rb
##   Desc:   End Case Command
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class EndCase < IseMessage
  def initialize
    super
    desc "End Case Command"
     item(:ACE_INT32, :case_number_)
  end
end
