###############################################
###
##   File:   EndEngagement.rb
##   Desc:   Model is at End of Engagement
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class EndEngagement < IseMessage
  def initialize
    super
    desc "Model is at End of Engagement"
  end
end
