###############################################
###
##   File:   EndFrame.rb
##   Desc:   Model has reached the end of compute frame
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class EndFrame < IseMessage
  def initialize
    super
    desc "Model has reached the end of compute frame"
  end
end
