###############################################
###
##   File:   EndRun.rb
##   Desc:   End Run Command
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class EndRun < IseMessage
  def initialize
    super
    desc "End Run Command"
  end
end
