###############################################
###
##   File:   EndRunComplete.rb
##   Desc:   End Run Completed
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class EndRunComplete < IseMessage
  def initialize
    super
    desc "End Run Completed"
  end
end
