###############################################
###
##   File:   InitCase.rb
##   Desc:   Initialize Case
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class InitCase < IseMessage
  def initialize
    super
    desc "Initialize Case"
     item(:ACE_INT32, :case_number_)
     item(:bool, :separate_advance_time_)
     item(:bool, :send_end_frame_)
  end
end
