###############################################
###
##   File:   InitEvent.rb
##   Desc:   InitEvent
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class InitEvent < IseMessage
  def initialize
    super
    desc "InitEvent"
  end
end
