###############################################
###
##   File:   InitCaseComplete.rb
##   Desc:   Initialize Case Completed
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class InitCaseComplete < IseMessage
  def initialize
    super
    desc "Initialize Case Completed"
  end
end
