###############################################
###
##   File:   PauseSimulation.rb
##   Desc:   Send to run master to pause the simulation after the current frame
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class PauseSimulation < IseMessage
  def initialize
    super
    desc "Send to run master to pause the simulation after the current frame"
  end
end
