###############################################
###
##   File:   RegisterEndEngage.rb
##   Desc:   Model is registering to send and End of Engagement
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class RegisterEndEngage < IseMessage
  def initialize
    super
    desc "Model is registering to send and End of Engagement"
  end
end
