###############################################
###
##   File:   Shutdown.rb
##   Desc:   This model is shutting down
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class Shutdown < IseMessage
  def initialize
    super
    desc "This model is shutting down"
  end
end
