###############################################
###
##   File:   StartFrame.rb
##   Desc:   Start a compute frame
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class StartFrame < IseMessage
  def initialize
    super
    desc "Start a compute frame"
  end
end
