###############################################
###
##   File:   StartSimulation.rb
##   Desc:   Send to run master to start the simulation
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class StartSimulation < IseMessage
  def initialize
    super
    desc "Send to run master to start the simulation"
  end
end
