###############################################
###
##   File:   TimeAdvanced.rb
##   Desc:   Time was Advanced
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class TimeAdvanced < IseMessage
  def initialize
    super
    desc "Time was Advanced"
  end
end
