###############################################
###
##   File:   ThreatDestroyed.rb
##   Desc:   Target Destroyed End Engagement
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class ThreatDestroyed < IseMessage
  def initialize
    super
    desc "Target Destroyed End Engagement"
    item(:double,          :time_)
    item(:ascii_string32,  :threat_label_)
  end
end
