/*
 *	File:	ISERelease.h
 *	Desc:	Marks the release
 *		This file is automatically generated.
 *
 * <Insert ChangeLog Here>
 * 
 */


#ifndef ISERELEASE_H
#define ISERELEASE_H

#define ISE_RELEASE "$State: 1/branches/edge $"

const char gcISERELEASE[] = ISE_RELEASE;

#endif
